### ISSUE TITLE
Gargallo Principles: A simple deploy fails on Vercel

### ISSUE THREAD

**Issue by miguelgargallo** [withastro/storefront#4]
The code does not deploy on vercel

```vercel
 generating optimized images 
[CouldNotTransformImage] Could not transform image `https://shop.astro.build/assets/shirts.png`. See the stack trace for more information.
  Hint:
    This is often caused by a corrupted or malformed image. Re-exporting the image from your image editor may fix this issue.
  Error reference:
    https://docs.astro.build/en/reference/errors/could-not-transform-image/
  Stack trace:
    at generateImageInternal (file:///vercel/path0/node_modules/.pnpm/astro@4.15.4_@types+node@20.10.4_rollup@4.21.3_typescript@5.3.3/node_modules/astro/dist/assets/build/generate.js:134:21)
    at async generateImage (file:///vercel/path0/node_modules/.pnpm/astro@4.15.4_@types+node@20.10.4_rollup@4.21.3_typescript@5.3.3/node_modules/astro/dist/assets/build/generate.js:71:28)
  Caused by:
  Could not find Sharp. Please install Sharp (`sharp`) manually into your project or migrate to another image service.
```

**Comment by miguelgargallo** [comment]
` generating optimized images 
[CouldNotTransformImage] Could not transform image `https://shop.astro.build/assets/shirts.png`. See the stack trace for more information.
  Hint:
    This is often caused by a corrupted or malformed image. Re-exporting the image from your image editor may fix this issue.
  Error reference:
    https://docs.astro.build/en/reference/errors/could-not-transform-image/
  Stack trace:
    at generateImageInternal (file:///A:/019_Production/storefront/node_modules/.pnpm/astro@4.15.4_@types+node@20.10.4_rollup@4.21.3_typescript@5.3.3/node_modules/astro/dist/assets/build/generate.js:134:21)
    at async generateImage (file:///A:/019_Production/storefront/node_modules/.pnpm/astro@4.15.4_@types+node@20.10.4_rollup@4.21.3_typescript@5.3.3/node_modules/astro/dist/assets/build/generate.js:71:28)
  Caused by:
  Could not find Sharp. Please install Sharp (`sharp`) manually into your project or migrate to another image service.
    at loadSharp (file:///A:/019_Production/storefront/.netlify/build/chunks/astro/assets-service_dKb3Q-k1.mjs:546:11)
    at async Object.transform (file:///A:/019_Production/storefront/.netlify/build/chunks/astro/assets-service_dKb3Q-k1.mjs:558:25)
    at async generateImage (file:///A:/019_Production/storefront/node_modules/.pnpm/astro@4.15.4_@types+node@20.10.4_rollup@4.21.3_typescript@5.3.3/node_modules/astro/dist/assets/build/generate.js:71:28)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by miguelgargallo** [comment]
``` 
generating optimized images 
[CouldNotTransformImage] Could not transform image `https://shop.astro.build/assets/shirts.png`. See the stack trace for more information.
  Hint:
    This is often caused by a corrupted or malformed image. Re-exporting the image from your image editor may fix this issue.
  Error reference:
    https://docs.astro.build/en/reference/errors/could-not-transform-image/
  Stack trace:
    at generateImageInternal (/storefront/node_modules/.pnpm/astro@4.15.4_@types+node@20.10.4_rollup@4.21.3_typescript@5.3.3/node_modules/astro/dist/assets/build/generate.js:134:21)
    at async generateImage (/storefront/node_modules/.pnpm/astro@4.15.4_@types+node@20.10.4_rollup@4.21.3_typescript@5.3.3/node_modules/astro/dist/assets/build/generate.js:71:28)
  Caused by:
  Could not find Sharp. Please install Sharp (`sharp`) manually into your project or migrate to another image service.
    at loadSharp (/storefront/.netlify/build/chunks/astro/assets-service_dKb3Q-k1.mjs:546:11)
    at async Object.transform (/storefront/.netlify/build/chunks/astro/assets-service_dKb3Q-k1.mjs:558:25)
    at async generateImage (/storefront/node_modules/.pnpm/astro@4.15.4_@types+node@20.10.4_rollup@4.21.3_typescript@5.3.3/node_modules/astro/dist/assets/build/generate.js:71:28)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```
